// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package injection

import (
	"github.com/Shodocan/UserService/internal/configs"
	"github.com/Shodocan/UserService/internal/database"
	"github.com/Shodocan/UserService/internal/domain/usecase"
	"github.com/Shodocan/UserService/internal/services"
)

// Injectors from wire.go:

func InitializeUserCase(config *configs.EnvVarConfig, db database.MongoDB) *usecase.UserCase {
	userService := services.NewUserServiceMongo(db, config)
	logger := configs.NewLog()
	userCase := usecase.NewUserCase(config, userService, logger)
	return userCase
}
