run:
  build-tags:
    - integration

linters-settings:

linters:
  # Enable extra linters besides the default ones
  enable:
    - bodyclose
    - goimports
    - goconst
    - govet
    - stylecheck
    - unconvert
    - unparam
    - misspell
    - whitespace
