version: '3'

services:
  mongo:
    image: mongo:4.4.4-bionic
    ports:
      - 27017:27017
    networks:
      - user-service
    volumes:
      - db-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: user

  redis:
    image: redislabs/rejson:1.0.7
    ports:
      - 6379:6379
    networks:
      - user-service
    

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - user-service
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: root

  user-service:
    image: walissoncasonatto/user-service:local
    ports:
      - "8080:8080"
    networks:
      - user-service
    healthcheck:
      test: curl http://127.0.0.1:8080/_healthz
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MONGODB_HOST: mongo
      MONGODB_ADMINUSERNAME: mongo
      MONGODB_ADMINPASSWORD: root
      MONGODB_DATABASE: user
      REDISDB_ACTIVE: "true"
      REDISDB_HOST: redis
      REDISDB_PORT: 6379
      REDISDB_PASSWORD: ""
      REDISDB_DATABASE: 1
    entrypoint:
      - /user-service
    depends_on:
      - mongo
      - redis
  

volumes:
  db-data:

networks: 
  user-service: