apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  log-level: "{{ .Values.configs.loglevel }}"
  db-name: "{{ .Values.configs.dbname }}"
  db-host: "{{ .Values.configs.dbhost }}"
  db-port: "{{ .Values.configs.dbport }}"
  living-time: {{ .Values.configs.livingtime }}