replicaCount: 4

image:
  repository: walissoncasonatto/instance-inventory-api:27
  repositoryDB: walissoncasonatto/instance-inventory-db:27

service:
  port: 80

resources:
  limits:
    cpu: 80m
    memory: 64Mi
  requests:
    cpu: 40m
    memory: 32Mi
  
configs:
  loglevel: Debug
  dbname: Instance
  dbhost: inventory-db-service.default.svc.cluster.local
  dbport: 27017
  livingtime: 1200s

